# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  
      - run: cd client
      - name: create client docker image
        run: docker build -t "rkakumar85/movie-app-automated:"react-app"
      - run: cd..
      - run: cd server
      - name: Change to Server Directory and create docker image
        run: docker build -t "rkakumar85/movie-app-automated:"api-server"
      - run: cd..
      - name: Push to Dockerr hub
        run: docker push rkakumar85/movie-app-automated
