# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      - name: Change directory and create client docker image
        working-directory: ./client
        run: docker build -t "rkakumar85/movie-app-automated:"react-app"
      - name: Change directory
        run: cd..
      - name: Change to Server Directory and create docker image
        working-directory: ./server
        run: docker build -t "rkakumar85/movie-app-automated:"api-server"
      - name: Get to root server
        run: docker push rkakumar85/movie-app-automated
